# Generated by Django 3.2.3 on 2022-01-16 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CongressPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bioguide', models.CharField(max_length=100, unique=True)),
                ('firstName', models.CharField(max_length=1000)),
                ('lastName', models.CharField(max_length=1000)),
                ('fullName', models.CharField(max_length=1000)),
                ('currentParty', models.CharField(max_length=100)),
                ('currentChamber', models.CharField(max_length=100)),
                ('currentState', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=10000)),
                ('termsServed', models.JSONField(blank=True, default=None, null=True)),
                ('totalTransactions', models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=100, unique=True)),
                ('company', models.CharField(max_length=1000)),
                ('market', models.CharField(max_length=20)),
                ('sector', models.CharField(max_length=1000)),
                ('industry', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CongressTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionDate', models.DateField(blank=True, null=True)),
                ('disclosureDate', models.DateField(blank=True, null=True)),
                ('transactionType', models.CharField(blank=True, max_length=60)),
                ('amount', models.CharField(blank=True, max_length=60)),
                ('owner', models.CharField(max_length=60)),
                ('assetDescription', models.CharField(blank=True, max_length=1000)),
                ('assetType', models.CharField(blank=True, max_length=1000)),
                ('ptrLink', models.CharField(max_length=100)),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('pdf', models.BooleanField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congress.congressperson')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congress.ticker')),
            ],
            options={
                'ordering': ['-transactionDate'],
                'unique_together': {('disclosureDate', 'transactionDate', 'owner', 'ticker', 'assetDescription', 'assetType', 'transactionType', 'amount', 'comment', 'name', 'pdf', 'ptrLink')},
            },
        ),
    ]
