# Generated by Django 3.2.3 on 2022-01-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0002_auto_20220116_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='congresstrade',
            name='assetDetails',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
