# Generated by Django 3.2.3 on 2022-01-16 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0003_congresstrade_assetdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congresstrade',
            name='ticker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='congress.ticker'),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='marketcap',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
