# Generated by Django 3.2.6 on 2022-01-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0004_auto_20220116_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalTransactions', models.IntegerField(default=0, editable=False)),
                ('purchases', models.IntegerField(default=0, editable=False)),
                ('sales', models.IntegerField(default=0, editable=False)),
                ('totalVolume', models.IntegerField(default=0, editable=False)),
                ('timeframe', models.IntegerField(default=0, editable=False)),
            ],
        ),
    ]
