# Generated by Django 3.2.6 on 2022-01-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0006_rename_summarystats_summarystat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarystat',
            name='purchases',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summarystat',
            name='sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summarystat',
            name='timeframe',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='summarystat',
            name='totalTransactions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summarystat',
            name='totalVolume',
            field=models.IntegerField(default=0),
        ),
    ]
