# Generated by Django 3.2.6 on 2022-01-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0009_alter_summarystat_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarystat',
            name='timeframe',
            field=models.IntegerField(unique=True),
        ),
    ]
