# Generated by Django 3.2.6 on 2022-01-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0010_alter_summarystat_timeframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='congressperson',
            name='purchases',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='congressperson',
            name='sales',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='congressperson',
            name='totalVolumeTransactions',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='purchases',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='sales',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='totalTransactions',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='totalVolumeTransactions',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='congressperson',
            name='totalTransactions',
            field=models.IntegerField(default=0),
        ),
    ]
