# Generated by Django 3.2.6 on 2022-01-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0011_auto_20220118_2357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congresstrade',
            options={},
        ),
        migrations.AlterField(
            model_name='congressperson',
            name='purchases',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='congressperson',
            name='sales',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='congressperson',
            name='totalTransactions',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='congressperson',
            name='totalVolumeTransactions',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='summarystat',
            name='purchases',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summarystat',
            name='sales',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summarystat',
            name='timeframe',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='summarystat',
            name='total',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summarystat',
            name='totalVolume',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='marketcap',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='purchases',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='sales',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='totalTransactions',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='totalVolumeTransactions',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='congresstrade',
            unique_together=set(),
        ),
    ]
