# Generated by Django 3.2.3 on 2022-01-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='market',
        ),
        migrations.AddField(
            model_name='ticker',
            name='marketcap',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
