# Generated by Django 3.2.6 on 2022-01-18 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0008_rename_totaltransactions_summarystat_total'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='summarystat',
            unique_together={('total', 'purchases', 'sales', 'totalVolume', 'timeframe')},
        ),
    ]
