# Generated by Django 3.2.3 on 2022-01-21 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0012_auto_20220120_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congresstrade',
            options={'ordering': ['-transactionDate']},
        ),
        migrations.AlterUniqueTogether(
            name='congresstrade',
            unique_together={('disclosureDate', 'transactionDate', 'owner', 'ticker', 'assetDescription', 'assetType', 'transactionType', 'amount', 'comment', 'name', 'pdf', 'ptrLink')},
        ),
    ]
