# Generated by Django 3.2.3 on 2022-01-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0013_auto_20220121_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congressperson',
            name='fullName',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='congressperson',
            name='purchases',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='congressperson',
            name='sales',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='congressperson',
            name='totalTransactions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='congressperson',
            name='totalVolumeTransactions',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='purchases',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='sales',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='totalTransactions',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='totalVolumeTransactions',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
