# Generated by Django 3.2.3 on 2022-01-24 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0014_auto_20220123_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congressperson',
            name='bioguide',
        ),
        migrations.RemoveField(
            model_name='congressperson',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='congressperson',
            name='lastName',
        ),
    ]
