# Generated by Django 3.2.3 on 2022-01-24 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0016_auto_20220123_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congressperson',
            name='termsServed',
        ),
    ]
