# @Author: Farhan Rehman
# Purpose: Registering app (congress folder) with django

# Import Libraries
from django.apps import AppConfig
from django.conf import settings

# Standard App config (generated by django)
class CongressConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'congress'

    # Function to run when the app is loaded, in order to call the schduling functions to start updating the databse every day
    def ready(self):
        from api import operator
        if settings.SCHEDULER_DEFAULT:
            operator.start()

